# Generated by Django 2.1.5 on 2019-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_document_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.TextField(help_text='Enter a comment.', max_length=500, null=True),
        ),
    ]
