# Generated by Django 2.1.5 on 2019-02-05 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_document_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ip_address',
            field=models.TextField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
