# Generated by Django 2.1.5 on 2019-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190205_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ip_address',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
