# Generated by Django 2.1.5 on 2019-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190205_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.TextField(help_text='Enter a comment.', max_length=150, null=True),
        ),
    ]
